# frontend/cloudbuild.yaml

steps:
  # Step 1: Install all frontend dependencies.
  # The 'dir' property tells Cloud Build to run this command inside the /frontend directory.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'
    id: 'InstallDependencies'

  # Step 2: Create the .env file and then build the application.
  # This step also runs inside the /frontend directory.
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    id: 'BuildApp'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "VITE_FIREBASE_API_KEY=$${_FIREBASE_API_KEY}" >> .env
        echo "VITE_FIREBASE_AUTH_DOMAIN=$${_FIREBASE_AUTH_DOMAIN}" >> .env
        echo "VITE_FIREBASE_PROJECT_ID=$${_FIREBASE_PROJECT_ID}" >> .env
        echo "VITE_FIREBASE_STORAGE_BUCKET=$${_FIREBASE_STORAGE_BUCKET}" >> .env
        echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$${_FIREBASE_MESSAGING_SENDER_ID}" >> .env
        echo "VITE_FIREBASE_APP_ID=$${_FIREBASE_APP_ID}" >> .env
        npm run build
    secretEnv:
      - '_FIREBASE_API_KEY'
      - '_FIREBASE_AUTH_DOMAIN'
      - '_FIREBASE_PROJECT_ID'
      - '_FIREBASE_STORAGE_BUCKET'
      - '_FIREBASE_MESSAGING_SENDER_ID'
      - '_FIREBASE_APP_ID'

  # Step 3: Deploy the built files to Google Cloud Storage.
  # The source path is now correctly pointing to 'frontend/dist'.
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-c'
      - '-d'
      - 'frontend/dist' # This is the corrected source path
      - 'gs://shifted-project-os-deployment-website'
    id: 'DeployToGCS'

# This section maps secrets from Secret Manager to variables for the build step.
availableSecrets:
  secretManager:
    - versionName: projects/shifted-project-os-deployment/secrets/firebase-api-key/versions/latest
      env: '_FIREBASE_API_KEY'
    - versionName: projects/shifted-project-os-deployment/secrets/firebase-auth-domain/versions/latest
      env: '_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/shifted-project-os-deployment/secrets/firebase-project-id/versions/latest
      env: '_FIREBASE_PROJECT_ID'
    - versionName: projects/shifted-project-os-deployment/secrets/firebase-storage-bucket/versions/latest
      env: '_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/shifted-project-os-deployment/secrets/firebase-messaging-sender-id/versions/latest
      env: '_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/shifted-project-os-deployment/secrets/firebase-app-id/versions/latest
      env: '_FIREBASE_APP_ID'

timeout: '1200s'